#!/bin/bash

# halt the main process if it is running on the pi, then cleanup neopixel
# CAUTION: this will halt all processes by root with python3\ main.py in its current state

sudo pkill -f -u root python3\ main.py
sudo python3 /home/pi/projects/neopixel_project/main.py -cleanup