#!/bin/bash
# halt the main process if it is running on the pi, then cleanup neopixel
# CAUTION: this will halt all python3 processes
echo "Killing main.py"
sudo pkill -f python3
sudo python3 /home/pi/projects/neopixel_project/main.py -cleanup
